workflow testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -158,7 +158,8 @@ jobs:
             git checkout master || { echo "Git checkout failed"; exit 1; }
             git pull origin master || { echo "Git pull failed"; exit 1; }
             echo "Current commit: $(git rev-parse HEAD)"
-            npm ci --legacy-peer-deps || { echo "npm ci failed"; exit 1; }
+            # npm ci --legacy-peer-deps || { echo "npm ci failed"; exit 1; }
+            npm ci
             npm run build || { echo "Build failed"; exit 1; }
             echo "Built files:"
             ls -la .next
